title: Arcada
description:
show_downloads: no

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://0jonjo.github.io/arcada" # change this to the base hostname & protocol for your site


google_analytics: G-EB41YV9XGD

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%-d-%m-%Y"

theme: # leave it empty

# social
author: Jo√£o Gilberto N. Saraiva
image:
twitter:
  username: 0jonjo

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['send', 'about', 'contact']
